<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- <ItemGroup>
    <Content Remove="Data\people.json" />
    <Content Remove="Data\performances.json" />
    <Content Remove="Data\reservations.json" />
  </ItemGroup> -->

  <!-- <ItemGroup>
    <None Include="CircusLunaLibrary\Data\people.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="CircusLunaLibrary\Data\performances.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="CircusLunaLibrary\Data\reservations.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup> -->

  <ItemGroup>
    <None Include="Data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Data\venues.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CircusLunaLibrary\CircusLunaLibrary.csproj" />
  </ItemGroup>

</Project>
